name: develop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      pull-requests: write

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        run: |
          corepack enable
          pnpm --version
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Unit Test
        run: pnpm test:coverage
      - name: Report Coverage
        uses:  davelosert/vitest-coverage-report-action@v2
      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
          exitZeroOnChanges: true
